### ISSUE TITLE
Missing Translation Strings for Partials

### ISSUE THREAD

**Issue by mcab** [tablexi/nucore-open#1496]
**Problem**: When trying to edit a reconcilable order, the edit order dialog never loads due to a missing translation string.

<img width="998" alt="screen shot 2018-04-13 at 6 41 16 pm" src="https://user-images.githubusercontent.com/4522043/38760596-51bae9aa-3f4a-11e8-8283-6e904c35ba67.png">

I believe it's because the partial view isn't aware of the current `order_management.order_details.edit.remove_from_journal` translation string. The quick fix would be to write one for the `shared_details` partial view, but could possibly be overlooked when refactoring. I'm not sure how to have the partial view aware of this existing translation string, so I don't have a better suggestion.

**Comment by mcab** [comment]
**Problem**: When trying to Add a Recharge String to a Facility, another translation is found to be missing.

<img width="1002" alt="screen shot 2018-04-13 at 7 29 44 pm" src="https://user-images.githubusercontent.com/4522043/38761483-13de29ba-3f51-11e8-960c-1f326e4d29fb.png">

This is on 07d031c298084f28ea1f446fa509ea41e37646f0.

**Comment by jhanggi** [comment]
Thanks for catching these. The recharge account is a new one, but the remove from journal has been around for a while. 

The reason we never caught it is because`config.action_view.raise_on_missing_translations` is set to false on stage and production, while it's true on development. We should probably have it set to true in test as well.

We'll push up a fix for these shortly.
